version: "3.9"
services:
  pricebuddy:
    build:
      context: .
      dockerfile: docker/php.dockerfile
    image: jez500/pricebuddy:latest
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/storage:/app/storage
      - ${APP_DATA_DIR}/data/.env:/app/.env
    environment:
      DB_HOST: database                               # Name of the database service
      DB_DATABASE: pricebuddy                         # Should match the MYSQL_DATABASE in the database service
      DB_USERNAME: pricebuddy                         # Should match the MYSQL_USER in the database service
      DB_PASSWORD: ${DB_PASSWORD}                     # Should match the MYSQL_PASSWORD in the database service
      APP_USER_EMAIL: ${APP_USER_EMAIL}               # Only used for seeding the database
      APP_USER_PASSWORD: ${APP_USER_PASSWORD}         # Only used for seeding the database
      SCRAPER_BASE_URL: http://scraper:3000           # Url to Name of the scrapper service
      AFFILIATE_ENABLED: 'false'                      # See https://pricebuddy.jez.me/support-project.html
    depends_on:
      database:
        condition: service_healthy
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.pricebuddy-web-redirect.redirectscheme.scheme: https
      traefik.http.services.pricebuddy.loadbalancer.server.port: 80
      # Web
      traefik.http.routers.pricebuddy-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.pricebuddy-insecure.entrypoints: web
      traefik.http.routers.pricebuddy-insecure.service: pricebuddy
      traefik.http.routers.pricebuddy-insecure.middlewares: pricebuddy-web-redirect
      # Websecure
      traefik.http.routers.pricebuddy.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.pricebuddy.entrypoints: websecure
      traefik.http.routers.pricebuddy.service: pricebuddy
      traefik.http.routers.pricebuddy.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.pricebuddy-local-insecure.rule: Host(`pricebuddy.${LOCAL_DOMAIN}`)
      traefik.http.routers.pricebuddy-local-insecure.entrypoints: web
      traefik.http.routers.pricebuddy-local-insecure.service: pricebuddy
      traefik.http.routers.pricebuddy-local-insecure.middlewares: pricebuddy-web-redirect
      # Local domain secure
      traefik.http.routers.pricebuddy-local.rule: Host(`pricebuddy.${LOCAL_DOMAIN}`)
      traefik.http.routers.pricebuddy-local.entrypoints: websecure
      traefik.http.routers.pricebuddy-local.service: pricebuddy
      traefik.http.routers.pricebuddy-local.tls: true
      runtipi.managed: true

  database:
    image: mysql:8.2
    environment:
      MYSQL_DATABASE: pricebuddy
      MYSQL_USER: pricebuddy
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/database:/var/lib/mysql
    networks:
      - tipi_main_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  scraper:
    image: amerkurev/scrapper:latest
    restart: unless-stopped
    networks:
      - tipi_main_network

volumes:
  storage:
  database:

networks:
  tipi_main_network:
